### ISSUE TITLE
openapi2jsonschema.py strips group to first subdomain

### ISSUE THREAD

**Issue by james-callahan** [yannh/kubeconform#130]
I'm trying to use `FILENAME_FORMAT='{group}-{version}-{kind}'`. I would have expected this to work with `-schema-location './crd-schemas/{{ .Group }}-{{ .ResourceAPIVersion }}-{{ .ResourceKind }}.json'`. However for some reason openapi2jsonschema.py splits the group on `.` and only uses the first component: https://github.com/yannh/kubeconform/blob/3cb76bc5e623903363d016fe4ce60036a42ee01a/scripts/openapi2jsonschema.py#L154

This means that it ends up creating `monitoring-v1-prometheus.json`, but kubeconform looks for `monitoring.coreos.com-v1-prometheus.json`

**Comment by yannh** [comment]
Apologies if I am slow to reply to requests with regards to this script - I do not understand it well enough and would need to have a number of unit tests to be sure changes do not break existing workflows. I actively rely on this script which is why I am conservative with changes. Thanks for your patience :bow:

**Comment by rgarcia89** [comment]
Same happens to me. When I run the crd-extractor.sh script the CRD `admissionreports.kyverno.io.yaml` is converted by the openapi2jsonschema to `kyverno.io-v1alpha2.json`. Since there are multiple kyverno CRDs only the last one remains in the json schema. However, if I go and run `python3 $TMP_CRD_DIR/openapi2jsonschema.py $TMP_CRD_DIR/*.yaml
` manually everything works fine. 

```
./crd-extractor.sh
JSON schema written to kyverno.io-v1alpha2.json
JSON schema written to monitoring.coreos.com-v1alpha1.json
JSON schema written to monitoring.coreos.com-v1.json
...
```

```
python3 $TMP_CRD_DIR/openapi2jsonschema.py $TMP_CRD_DIR/*.yaml
JSON schema written to admissionreport_v1alpha2.json
JSON schema written to alertmanagerconfig_v1alpha1.json
JSON schema written to alertmanager_v1.json
...
```
