### ISSUE TITLE
Support multi-architecture Docker image

### ISSUE THREAD

**Issue by denisa** [yannh/kubeconform#196]
Apple is transitioning its computer to a arm64 architecture

While amd64 can be executed, sometime, this is slower.

Could the project build an image that supports both amd64 and arm64?.

**Comment by yannh** [comment]
What would you think of arm64 images, like with a -arm64 suffix? That should be pretty trivial to add :)

**Comment by denisa** [comment]
Do you mean https://goreleaser.com/cookbooks/multi-platform-docker-images/?h=multi ?

In the ideal end-state, there is a single image and docker dynamically downloads what’s appropriate at execution time

**Comment by yannh** [comment]
I tried adding support for separate arm64 images here https://github.com/yannh/kubeconform/actions/runs/4971934488/jobs/8896808560 but hit some issues and reverted for now. This is also pretty difficult for me to test - since I do not own a mac. 
I don't have much more time today, but would happily merge PRs to add support here. Also happy to add support for multi-arch images.

**Comment by denisa** [comment]
I’ll give it a try this weekSent from my iPadOn May 14, 2023, at 03:55, Yann Hamon ***@***.***> wrote:﻿
I tried adding support for separate arm64 images here https://github.com/yannh/kubeconform/actions/runs/4971934488/jobs/8896808560 but hit some issues and reverted for now. This is also pretty difficult for me to test - since I do not own a mac.
I don't have much more time today, but would happily merge PRs to add support here. Also happy to add support for multi-arch images.

**Comment by denisa** [comment]
See https://github.com/yannh/kubeconform/pull/204

**Comment by yannh** [comment]
Closing, since the PR has been merged, thanks!

**Comment by yannh** [comment]
Closing, since the PR has been merged, thanks!
