### ISSUE TITLE
could not find schema for SecretProviderClass"

### ISSUE THREAD

**Issue by KylanZhang** [yannh/kubeconform#227]
+ /home/jenkins/kubeconform -summary '-output=json' dep.yaml
{
  "resources": [
    {
      "filename": "dep.yaml",
      "kind": "SecretProviderClass",
      "name": "n-jenkins",
      "version": "secrets-store.csi.x-k8s.io/v1alpha1",
      "status": "statusError",
      **"msg": "could not find schema for SecretProviderClass"**
    }
  ],
  "summary": {
    "valid": 4,
    "invalid": 0,
    "errors": 1,
    "skipped": 0
  }
}

**Comment by savf** [comment]
This is expected behaviour since the schema repository cannot cover all possible schemas. You can however add your own OpenAPI schemas with the parameter: `-schema-location "crdSchemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json"` where `crdSchemas` would contain the individual JSON schemas, for example `secretproviderclass_v1.json` for the SecretProviderClass schema.

You can get the schema JSON directly from deployed CRDs from your cluster, e.g.:
```
kubectl get crd/secretproviderclasses.secrets-store.csi.x-k8s.io -o json | jq '.spec.versions[]?.schema.openAPIV3Schema'
```

**Comment by yannh** [comment]
As @savf suggested, or you could also use this repository which collects the most common CRDs: https://github.com/datreeio/CRDs-catalog !
