### ISSUE TITLE
Schema validation silently fails for non-existent Kubernetes version

### ISSUE THREAD

**Issue by Niksko** [yannh/kubeconform#32]
Tried to do validation against K8s 1.19, which as per my other issue, isn't in the default schema repo. Instead of throwing an error, this seemed to just silently fail and skip validation of all resources.

Steps to reproduce:

```
$ kubeconform -ignore-missing-schemas -kubernetes-version 1.19.0 -summary
Summary: 964 resources found in 450 files - Valid: 0, Invalid: 0, Errors: 0, Skipped: 964
```

Expected result:
Some sort of error because the 1.19 schemas don't exist.

Presumably this is because I'm passing `-ignore-missing-schemas`? However if I don't pass `-ignore-missing-schemas`, I just get `Summary: 964 resources found in 450 files - Valid: 0, Invalid: 0, Errors: 964, Skipped: 0`.

**Comment by yannh** [comment]
Hi @Niksko , this seems to work as expected? If you ignore missing schemas, it will skip resources for which it doesnt find a shema - in this case all of them. If you do not pass -ignore-missing-schemas, it will error when it doesnt find a schema for a resource - in this case for all of them...

I would recommend you use -skip to explicitly ignore the kinds for which you know you do not have a schema, so that you don't get these silent errors as when using -ignore-missing-schemas.

**Comment by yannh** [comment]
I will close this since it is working as expected - a Kubernetes version missing should trigger a "schema not found" - I can't get kubeconform to fail on it, since you might be specifying multiple schema locations... I hope you found a way to get this to work with -skip :)
