### ISSUE TITLE
Help with locally stored schemas

### ISSUE THREAD

**Issue by svmundada** [yannh/kubeconform#48]
For validating CRDs I have been trying to set up schemas locally in a directory. 
My setup:

1. `kustomize fetch openapi > openapi.json`
2. From `openapi.json`, I have extracted value corresponding to `com.coreos.monitoring.v1.ServiceMonitor` and stored it in `/tmp/schemas/servicemonitor.json`
3. `cat sm.yaml | kubeconform --strict  --kubernetes-version 1.19.10  -schema-location '/tmp/schemas/{{ .ResourceKind }}.json'`

Output: `stdin - ServiceMonitor sm failed validation: Object has no key 'definitions'`

Data:
```
$ cat sm.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm
  namespace: observability
  labels:
    app: sm
spec:
  selector:
    matchLabels:
      app: sm
  namespaceSelector:
    any: true
  endpoints:
  - port: http
    path: /actuator/prometheus
```

Schema file - [servicemonitor.json.txt](https://github.com/yannh/kubeconform/files/6495776/servicemonitor.json.txt) (Uploaded as txt but used as JSON due to GitHub constraints ).

Been stuck here for a long time, Any help would be much appreciated.

**Comment by yannh** [comment]
Hi @svmundada , I think it might have to do with your schema file: it contains this: 

      "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta",

And that reference to definitions might be missing -  I suspect your schema is not valid.

From your command "kustomize fetch openapi"  I guess it might return an openapi schema, which you would need to convert to jsonschema using https://github.com/yannh/openapi2jsonschema first (kubeconform, like kubeval, uses jsonschema and not openapi for validation, mostly due to availability of validation libraries).

If this is for the Prometheus operators, these are the openapi files I use: https://github.com/prometheus-operator/prometheus-operator/tree/master/example/prometheus-operator-crd  :

$ openapi2jsonschema https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
JSON schema written to servicemonitor_v1.json

^ This is the file to validate against.

I'll leave this open - good luck!

**Comment by svmundada** [comment]
Hi @yannh, Thanks for your reply, I understand the process better but still stuck.

I tried this `openapi2jsonschema openapi.json  --kubernetes --strict --stand-alone --expanded` and it created `schemas/servicemonitor-monitoring-v1.json`. My requirement is to have multiple apiversions that's why using `--expanded`.


Can you please tell what would be the correct template string ? I tried this  `schemas/{{ .ResourceKind }}{{ .KindSuffix }}-{{ .ResourceAPIVersion}}.json` but its not working.

**Comment by yannh** [comment]
Well done! You can provide several -schema-locations:

 kubeconform -schema-location 'schemas/{{ .ResourceKind }}{{ .KindSuffix }}.json'  -schema-location default  .....

Default is an alias for this repository: https://github.com/yannh/kubernetes-json-schema  , and Kubeconform will download the files as required.  Kubeconform will look into each of these "schema locations" and try to find a match for the schema.

I hope this helps, best,
Yann

**Comment by yannh** [comment]
Hi @svmundada , I ll be closing this for now since it looks like there is no issue with kubeconform itself. Let me know if I can maybe make the documentation better! :+1:
