### ISSUE TITLE
Renaming Arguments

### ISSUE THREAD

**Issue by volaka** [yannh/kubeconform#70]
Hi, 

Thanks for the great work!

I might be wrong but I didn't see any shortened args in the help docs. (e.g. -kubernetes-version -> -v, -verbose -> -V)

Do you think it is worth being added?

**Comment by yannh** [comment]
Renaming is hard and would break dramatically for everyone who is using the long form in their scripts... I am on the same page as https://superuser.com/questions/174564/why-are-there-short-and-long-alternatives-for-command-line-options  and believe long parameters are better since they re most explicit, at least when used in scripts: is -v the kubernetes version of the kubeconform version?

So while I get that it is different than Kubeval, I would err on keeping it this way.

**Comment by volaka** [comment]
My bad in using "renaming". I meant to say addind short-hand args for long-named ones. for example for -kubernetes-version we can also add -v option, so it wont break any pipelines but adds functionality

**Comment by yannh** [comment]
@volaka I'll use my maintainer privilege here and keep it this way :grimacing:  -v is ambiguous (it could be the version of kubeconform) and I think the benefit of having this alias does not outweigh the added complexity. I know Kubeconform differs a bit from Kubeval here - but kubeconform uses a different library for parameter parsing that makes this a tiny bit more difficult.

If there was ever a goal to unite both projects (see https://github.com/instrumenta/kubeval/issues/268 )  it might be worth making both CLIs compatibles, but it's a little bit of work, and there is little benefit otherwise.
